In [21]:
import pandas as pd
import random
import numpy as np

In [22]:
df = pd.read_csv("./jester-data-1.csv", header = None, delimiter = ",")

In [23]:
df.head()

0      1      2      3      4     5     6     7     8      9    ...    \
0   74  -7.82   8.79  -9.66  -8.16 -7.52 -8.50 -9.85  4.17  -8.98  ...     
1  100   4.08  -0.29   6.36   4.37 -2.38 -9.66 -0.73 -5.34   8.88  ...     
2   49  99.00  99.00  99.00  99.00  9.03  9.27  9.03  9.27  99.00  ...     
3   48  99.00   8.35  99.00  99.00  1.80  8.16 -2.82  6.21  99.00  ...     
4   91   8.50   4.61  -4.17  -5.39  1.36  1.60  7.04  4.61  -0.44  ...     

     91     92     93     94     95     96     97     98     99     100  
0   2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1   2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2  99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3  99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4   5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  

[5 rows x 101 columns]

In [24]:
print(df.shape)

# ROW. 
row_length = len(df.iloc[:,0])
print("row length = " + str(row_length))
# OR: df.shape[0]

# COLUMN. 
column_length = len(df.iloc[0])
print(column_length)
# OR: df.shape[1]

(24983, 101)
row length = 24983
101


In [25]:
# Count numbers that are 99 in data. 
count99_array = (df.iloc[:,:] == 99).sum()
count99 = count99_array.sum()
print("Count of number that are 99 = " + str(count99))

Count of number that are 99 = 687926


In [26]:
# Calculate percent of numbers that are 99.
percent99 = count99 / row_length
print("Percent 99 in data = " + str(percent99))

Percent 99 in data = 27.53576431973742


In [27]:
# Count of non-99 numbers. 
non99_count = (row_length * column_length) - count99
print("Count of non 99 numbers = " + str(non99_count))

Count of non 99 numbers = 1835357


In [28]:
# Copy dataframe. 
df_copy = df.copy()

In [29]:
# Construct training data. 
number_of_new99 = round(non99_count * 0.1)
print("number of new 99 = " + str(number_of_new99))

number of new 99 = 183536.0


In [30]:
# Change random numbers to 99 in the copied data. 
counter = number_of_new99
while counter > 0:
    rnd_row = random.randint(0, row_length - 1)
    rnd_column = random.randint(0, column_length - 1)
    if df_copy.iloc[rnd_row][rnd_column] != 99:
        df_copy.at[rnd_row, rnd_column] = 99
        counter -= 1

In [31]:
# Count new numbers that are 99 in copied data. 
count99_array_2 = (df_copy.iloc[:,:] == 99).sum()
count99_2 = count99_array_2.sum()
print("Count of number that are 99 = " + str(count99_2))

Count of number that are 99 = 871462


In [77]:
# Generate some random weights. 

# TODO: Why us this = 2?
n_features = 2

user_ratings = df_copy.values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_features))

In [78]:
user_ratings

array([[ 74.  ,  -7.82,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [100.  ,   4.08,  -0.29, ...,   0.34,  -4.32,   1.07],
       [ 49.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       ...,
       [ 39.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 37.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 72.  ,   2.43,   2.67, ...,  99.  ,  99.  ,  99.  ]])

In [79]:
latent_user_preferences

array([[0.4552771 , 0.05177362],
       [0.82511913, 0.0262485 ],
       [0.97809441, 0.80988513],
       ...,
       [0.40123822, 0.46803585],
       [0.93960024, 0.61245479],
       [0.05159724, 0.92430726]])

In [80]:
latent_item_features

array([[0.53542866, 0.47936976],
       [0.18112815, 0.93430029],
       [0.34066096, 0.89193382],
       [0.03619259, 0.47267378],
       [0.15998641, 0.71321291],
       [0.70407051, 0.83884932],
       [0.77034782, 0.67652   ],
       [0.90378617, 0.56905584],
       [0.34242922, 0.07379558],
       [0.83261199, 0.99162345],
       [0.89913306, 0.04398479],
       [0.525995  , 0.65453466],
       [0.89470088, 0.86166966],
       [0.74027387, 0.14392061],
       [0.3165552 , 0.74480632],
       [0.21947845, 0.84849713],
       [0.44436886, 0.0745023 ],
       [0.86784444, 0.74764309],
       [0.28017414, 0.05417235],
       [0.0140237 , 0.82332528],
       [0.6263332 , 0.66206458],
       [0.25149364, 0.09442458],
       [0.81962551, 0.99841038],
       [0.2182528 , 0.66405159],
       [0.06138872, 0.36359541],
       [0.42548386, 0.75304807],
       [0.49866308, 0.09592866],
       [0.7001028 , 0.50594865],
       [0.57033003, 0.56990416],
       [0.10673589, 0.88729802],
       [0.

In [189]:
#to1 = latent_user_preferences.shape[0]
#to2 = latent_item_features[0]
to1 = 100 # 100 first jokes. 
to2 = 101 # 101 features. 
alpha = 0.001

In [190]:
import math
def predict_rating(user_id, item_id):
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    ret = user_preference.dot(item_preference)
    return ret

def train(user_id, item_id, rating, alpha = alpha):
    prediction_rating = predict_rating(user_id, item_id)
    err = alpha * (rating - prediction_rating)
    latent_user_preferences[user_id] += err * latent_item_features[item_id]
    latent_item_features[item_id] += err * latent_user_preferences[user_id]
    return err

def sgd(iterations = 1):
    print("start sgd")
    for iteration in range(0, iterations):
        error = []
        for user_id in range(0, to1):
            for item_id in range(0, to2):
                rating = user_ratings[user_id][item_id]
                if(not np.isnan(rating) and rating < 99):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()
        if(iteration % 10 == 0):
            print(mse)

In [191]:
# Reset arrays (due to bug...)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_features))

# Run sgd
sgd(100)

start sgd
5.8025510005946276e-05
2.3654850344928648e-05
2.292991678792611e-05
2.157623692712603e-05
1.9453956953141073e-05
1.838391925148656e-05
1.792157569730573e-05
1.7723633253662306e-05
1.7626677603709146e-05
1.757124695388066e-05


In [192]:
# Just prediction. 
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 7.70639831e+01, -5.34077653e+00, -5.09839683e+00, ...,
        -9.54424655e-01, -3.32398011e+00, -5.14346085e-01],
       [-1.11954959e+01,  3.96636429e+00,  4.16852637e+00, ...,
         1.49833361e+00,  2.52906187e+00,  1.84391420e+00],
       [ 4.88909359e+01,  8.40976699e+00,  9.44132104e+00, ...,
         4.42244422e+00,  5.45771938e+00,  6.21597529e+00],
       ...,
       [ 1.31432597e+01,  1.45901534e+00,  1.67667414e+00, ...,
         8.47190594e-01,  9.52986941e-01,  1.22643173e+00],
       [ 1.77879096e+01,  1.10124772e+00,  1.33084535e+00, ...,
         7.74377012e-01,  7.29640168e-01,  1.17553649e+00],
       [ 1.84194692e+01, -1.32274471e-01,  1.07911234e-02, ...,
         2.59521192e-01, -6.06318938e-02,  5.11576868e-01]])

In [197]:
# Validate the model. 
error = []
for user_id in range(0, to1):
    for item_id in range(0, to2):
        rating = user_ratings[user_id][item_id]
        if(not np.isnan(rating) and rating >= 99):
            # Predict
            prediction_rating = predict_rating(user_id, item_id)
            # Calculate error. 
            err = alpha * (rating - prediction_rating)
            error.append(err)

# Evaluate using MSE
mse = (np.array(error) ** 2).mean()
print("Number of tests: " + str(len(error)))
print("MSE = " + str(mse))

Number of tests: 3490
MSE = 0.00951848160929006
